import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import MapFrame from "../components/MapFrame";
import { useLang } from "../lib/i18n";
import { fetchProperties, propertyPhotos, type Property } from "../lib/supabase";
import "../extended-theme-options.css";

export type ExtendedThemeOption = "option9" | "option10" | "option11" | "option12" | "option13" | "option14" | "option15" | "option16" | "option17" | "option18";
type Props = { option: ExtendedThemeOption };
type Language = "ar" | "en";

type ThemeCopy = {
  number: string; style: string; actions: 1 | 2 | 3;
  ar: { title: string; intro: string; label: string; explore: string; detail: string; contact: string; section: string; note: string; map: string; path: string[] };
  en: { title: string; intro: string; label: string; explore: string; detail: string; contact: string; section: string; note: string; map: string; path: string[] };
};

const THEMES: Record<ExtendedThemeOption, ThemeCopy> = {
  option9: { number:"09", style:"market", actions:3, ar:{label:"سوق الرياض",title:"اختر إقامتك من أول نظرة.",intro:"واجهة مباشرة تجمع الصور الحقيقية، سعر البداية، ومسار واضح إلى تفاصيل كل إقامة.",explore:"استكشف الإقامات",detail:"الإقامة البارزة",contact:"تواصل معنا",section:"إقامات يمكنك البدء منها",note:"السعر الظاهر سعر بداية؛ يظهر السعر النهائي بعد اختيار التواريخ.",map:"شاهد الاختيارات على الخريطة",path:["شاهد المساحة","افتح التفاصيل","اختر التواريخ"]},en:{label:"RIYADH MARKET",title:"Choose your stay at first glance.",intro:"A direct experience that brings real imagery, starting price, and a clear route into each residence together.",explore:"Explore stays",detail:"Featured residence",contact:"Contact us",section:"Stays to begin with",note:"The visible figure is a starting price; the final price appears after dates are selected.",map:"See the selection on the map",path:["See the space","Open the details","Choose the dates"]}},
  option10: { number:"10", style:"atelier", actions:2, ar:{label:"Atelier Horizon",title:"مساحات تتحدث بهدوء.",intro:"نمط تحريري واسع للضيف الذي يريد أن يعيش الصورة قبل أن يفتح التفاصيل العملية.",explore:"عرض المجموعة",detail:"من داخل الإقامة",contact:"اطلب المساعدة",section:"تفاصيل تُرى قبل أن تُقرأ",note:"كل بطاقة تفتح صفحة الإقامة الفعلية مع الصور والتوفر والمسار المتاح للحجز.",map:"المكان جزء من القرار",path:["ابدأ بالصورة","راجع التفاصيل","تابع عند الجاهزية"]},en:{label:"HORIZON ATELIER",title:"Spaces that speak quietly.",intro:"A wide editorial style for guests who want to experience the image before opening the practical details.",explore:"View the collection",detail:"Inside the stay",contact:"Ask for help",section:"Details seen before they are read",note:"Every card opens the actual stay page with imagery, availability, and the available booking route.",map:"Place is part of the decision",path:["Begin with the image","Review the details","Continue when ready"]}},
  option11: { number:"11", style:"weekender", actions:1, ar:{label:"إقامة نهاية الأسبوع",title:"اختيار واحد، ثم مساحة للتنفس.",intro:"صفحة دافئة ذات إيقاع بطيء، تضع الإقامة البارزة ثم تقودك لبقية الخيارات دون ازدحام.",explore:"ابدأ بالإقامة",detail:"اختيار هذا الأسبوع",contact:"تواصل",section:"مساحات قريبة من أسلوبك",note:"تظل الصور والتفاصيل مرتبطة بكل وحدة، بينما تختار تواريخك داخل صفحتها.",map:"أين ستقيم؟",path:["شاهد الإقامة","تعرّف على الموقع","أكمل الحجز"]},en:{label:"THE WEEKENDER",title:"One choice, then room to breathe.",intro:"A warm, unhurried page that puts the featured stay first and leads gently to the remaining choices.",explore:"Begin with the stay",detail:"This week’s choice",contact:"Contact",section:"Spaces near your pace",note:"Photography and details stay tied to each residence while dates are chosen inside its page.",map:"Where will you stay?",path:["See the stay","Know the place","Continue to booking"]}},
  option12: { number:"12", style:"archive", actions:3, ar:{label:"أرشيف الإقامات",title:"كل إقامة لها صورتها الخاصة.",intro:"بنية أرشيفية واضحة تجمع الاختيار البصري، مواصفات الإقامة، ثم الخريطة في رحلة مرتبة.",explore:"افتح الأرشيف",detail:"بطاقة الإقامة",contact:"اسأل Horizon",section:"صفحات من الأرشيف",note:"لا توجد تقييمات مصطنعة هنا؛ تعتمد الصفحة على صور الوحدة وبياناتها فقط.",map:"من الأرشيف إلى الخريطة",path:["اختر بطاقة","اقرأ الحقائق","راجع تواريخك"]},en:{label:"STAY ARCHIVE",title:"Every stay has its own image.",intro:"A clear archival structure that moves from visual selection to stay facts and then the map in an ordered journey.",explore:"Open the archive",detail:"Stay card",contact:"Ask Horizon",section:"Pages from the archive",note:"There are no fabricated reviews here; the page relies only on the residence imagery and data.",map:"From archive to map",path:["Choose a card","Read the facts","Review your dates"]}},
  option13: { number:"13", style:"edit", actions:2, ar:{label:"Horizon Edit",title:"الرياض، من نافذة الإقامة.",intro:"تجربة مجلة حضرية كبيرة تجمع لقطة رئيسية، وحدات مختارة، ومسار عملي قصير للحجز.",explore:"اكتشف الاختيارات",detail:"اللقطة الرئيسية",contact:"تواصل مع الفريق",section:"اختيارات التحرير",note:"يمكنك فتح أي إقامة لرؤية سعرها حسب تواريخك قبل متابعة الحجز.",map:"المدينة حول الإقامة",path:["التقط الإحساس","قارن الاختيارات","اختر تواريخك"]},en:{label:"THE HORIZON EDIT",title:"Riyadh, from a stay’s window.",intro:"A large city-journal experience joining a lead image, selected stays, and a short practical route to booking.",explore:"Discover the edit",detail:"Lead image",contact:"Contact the team",section:"Editor’s selection",note:"Open any stay to see its date-based price before you continue to booking.",map:"The city around the stay",path:["Catch the feeling","Compare the selection","Choose your dates"]}},
  option14: { number:"14", style:"gallery", actions:3, ar:{label:"معرض الإقامات",title:"صور حقيقية، قرار أوضح.",intro:"معرض واسع يقود الصورة أولاً، ثم يقدّم كل ما تحتاجه للانتقال إلى صفحة الإقامة.",explore:"دخول المعرض",detail:"الصورة البارزة",contact:"تحدث معنا",section:"تنقّل بين المساحات",note:"تتبدل صور البانر تلقائياً من معرض وحدات Horizon المسجلة.",map:"اكتشف المناطق",path:["شاهد المعرض","اختر إقامة","تأكد من التواريخ"]},en:{label:"STAY GALLERY",title:"Real imagery, a clearer decision.",intro:"A wide gallery that leads with the image and then provides everything needed to move into the stay page.",explore:"Enter the gallery",detail:"Featured image",contact:"Talk to us",section:"Move through the spaces",note:"Hero imagery rotates automatically from the registered Horizon stay galleries.",map:"Discover the districts",path:["See the gallery","Choose a stay","Confirm your dates"]}},
  option15: { number:"15", style:"mapmaker", actions:1, ar:{label:"دليل المناطق",title:"ابدأ من الحي، ثم اختر المساحة.",intro:"تجربة مبنية حول موقع الإقامة، مع وحدات متصلة بالخريطة ونداء بسيط لبدء التصفح.",explore:"استكشف الخريطة",detail:"الموقع والإقامة",contact:"تواصل",section:"إقامات عبر الرياض",note:"المواقع المعروضة على مستوى الحي لحماية خصوصية المباني والوحدات.",map:"دليل Horizon للمناطق",path:["اختر حياً","شاهد الوحدة","انتقل للتواريخ"]},en:{label:"DISTRICT GUIDE",title:"Begin with the district, then choose the space.",intro:"A place-led experience with stays connected to the map and one simple invitation to start browsing.",explore:"Explore the map",detail:"Place and stay",contact:"Contact",section:"Stays across Riyadh",note:"Locations are shown at neighbourhood level to protect building and residence privacy.",map:"Horizon’s district guide",path:["Choose a district","See the stay","Move to dates"]}},
  option16: { number:"16", style:"compare", actions:3, ar:{label:"مقارنة هادئة",title:"ضع الاختيارات بجانب بعضها.",intro:"صفحة عملية لمن يريد المقارنة بين المساحة، الحي، الضيوف، وسعر البداية قبل فتح التفاصيل.",explore:"قارن الإقامات",detail:"اختيار للمقارنة",contact:"احتاج مساعدة",section:"قرارك، بطريقة أوضح",note:"ستبقى تفاصيل السعر النهائية مرتبطة بالتواريخ التي تختارها داخل كل صفحة إقامة.",map:"قارن بحسب المنطقة",path:["أضف اختياراً","راجع التفاصيل","افتح التواريخ"]},en:{label:"QUIET COMPARISON",title:"Place choices side by side.",intro:"A practical page for comparing space, district, guests, and starting price before opening the details.",explore:"Compare stays",detail:"Compare this stay",contact:"Need help",section:"Your decision, made clearer",note:"Final price details remain tied to the dates chosen inside each stay page.",map:"Compare by district",path:["Add a choice","Review the details","Open the dates"]}},
  option17: { number:"17", style:"neighbourhood", actions:2, ar:{label:"قربك من الرياض",title:"إقامتك جزء من المدينة.",intro:"واجهة تستكشف الوحدات من خلال الحي والصورة والتفاصيل العملية دون كشف مواقع المباني الخاصة.",explore:"شاهد الأحياء",detail:"إقامة في هذا الحي",contact:"اطلب اقتراحاً",section:"زوايا من الأحياء",note:"افتح صفحات الوحدات للتحقق من السعر والتوفر قبل متابعة الحجز.",map:"المناطق المختارة",path:["ابدأ بالحي","اكتشف الإقامة","اختر التواريخ"]},en:{label:"CLOSE TO RIYADH",title:"Your stay is part of the city.",intro:"An experience that explores residences through district, imagery, and practical details without exposing private building locations.",explore:"See the districts",detail:"A stay in this district",contact:"Ask for a suggestion",section:"Views from the districts",note:"Open the stay pages to check price and availability before continuing to booking.",map:"Selected districts",path:["Begin with the district","Discover the stay","Choose dates"]}},
  option18: { number:"18", style:"portfolio", actions:1, ar:{label:"Horizon Portfolio",title:"كل الإقامات في مشهد واحد.",intro:"ختام واسع للخيارات: مشهد غامر، بطاقات فعلية، خريطة، ونقطة وصول مباشرة لتفاصيل الإقامة.",explore:"عرض المحفظة",detail:"الوحدة الأولى",contact:"تواصل معنا",section:"مجموعة Horizon",note:"تتبدل الخلفية والصورة الرئيسية بسلاسة مع احترام إعداد تقليل الحركة في المتصفح.",map:"المجموعة على الخريطة",path:["شاهد المشهد","افتح التفاصيل","أكمل عند الجاهزية"]},en:{label:"HORIZON PORTFOLIO",title:"Every stay in one wide view.",intro:"A broad close to the options: immersive scene, real stay cards, a map, and a direct entry into the stay details.",explore:"View the portfolio",detail:"The first stay",contact:"Contact us",section:"The Horizon collection",note:"Background and hero image rotate smoothly while respecting browser reduced-motion preferences.",map:"The collection on the map",path:["See the scene","Open the details","Continue when ready"]}},
};

const ar = (lang: string) => lang === "ar";
const nameOf = (stay: Property, lang: string) => ar(lang) ? stay.name_ar || stay.name_en : stay.name_en || stay.name_ar;
const imageOf = (stay: Property) => propertyPhotos(stay)[0] || "";
const priceOf = (stay: Property, lang: string) => `${new Intl.NumberFormat(ar(lang) ? "ar-SA" : "en-US").format(stay.price_per_night)} ${ar(lang) ? "ر.س / ليلة" : "SAR / night"}`;
const factsOf = (stay: Property, lang: string) => `${stay.neighborhood || (ar(lang) ? "الرياض" : "Riyadh")} · ${stay.bedrooms ? `${stay.bedrooms} ${ar(lang) ? "غرف" : "beds"}` : (ar(lang) ? "استوديو" : "Studio")} · ${stay.max_guests} ${ar(lang) ? "ضيوف" : "guests"}`;

function useReducedMotion() {
  const [reduced, setReduced] = useState(false);
  useEffect(() => { const media = window.matchMedia("(prefers-reduced-motion: reduce)"); const update = () => setReduced(media.matches); update(); media.addEventListener("change", update); return () => media.removeEventListener("change", update); }, []);
  return reduced;
}

function RotatingHero({ stays, theme, lang }: { stays: Property[]; theme: ThemeCopy; lang: string }) {
  const [index, setIndex] = useState(0); const reduced = useReducedMotion(); const photos = useMemo(() => stays.slice(0, 6).map((stay) => ({ stay, image: imageOf(stay) })).filter((entry) => entry.image), [stays]);
  useEffect(() => { if (reduced || photos.length < 2) return; const timer = window.setInterval(() => setIndex((current) => (current + 1) % photos.length), 4000); return () => window.clearInterval(timer); }, [photos.length, reduced]);
  const active = photos[index] || photos[0]; const c = theme[ar(lang) ? "ar" : "en"];
  if (!active) return null;
  return <section className="extended-hero" aria-label={c.title}>
    <div className="extended-hero-media" aria-hidden="true">{photos.map((entry, photoIndex) => <img className={photoIndex === index ? "is-active" : ""} src={entry.image} alt="" key={`${entry.stay.id}-${entry.image}`} />)}</div>
    <div className="extended-hero-shade" />
    <div className="extended-hero-copy"><span className="extended-kicker">OPTION {theme.number} / {c.label}</span><h1>{c.title}</h1><p>{c.intro}</p><div className="extended-hero-actions"><Link to={`/property/${active.stay.slug}`} className="extended-action-primary">{c.explore} <b>→</b></Link>{theme.actions >= 2 && <a href="#extended-collection" className="extended-action-quiet">{c.detail}</a>}{theme.actions === 3 && <Link to="/contact" className="extended-action-quiet">{c.contact}</Link>}</div></div>
    <div className="extended-hero-caption"><span>{String(index + 1).padStart(2, "0")} / {String(photos.length).padStart(2, "0")}</span><strong>{nameOf(active.stay, lang)}</strong><b>{priceOf(active.stay, lang)}</b></div>
  </section>;
}

function PropertyCard({ stay, lang, large = false }: { stay: Property; lang: string; large?: boolean }) {
  return <article className={`extended-stay-card ${large ? "is-large" : ""}`}><Link to={`/property/${stay.slug}`}><img src={imageOf(stay)} alt={nameOf(stay, lang)} loading="lazy" /></Link><div><span>{factsOf(stay, lang)}</span><h3>{nameOf(stay, lang)}</h3><p>{ar(lang) && stay.description_ar ? stay.description_ar.slice(0, 115) : `${stay.area_m2 || "—"} m²`}</p><footer><b>{priceOf(stay, lang)}</b><Link to={`/property/${stay.slug}`}>{ar(lang) ? "التفاصيل" : "Details"} ↗</Link></footer></div></article>;
}

function DetailLayout({ theme, stays, lang }: { theme: ThemeCopy; stays: Property[]; lang: string }) {
  const c = theme[ar(lang) ? "ar" : "en"]; const lead = stays[0]; const layout = theme.style;
  return <>
    <section className={`extended-context extended-context-${layout}`}><div className="extended-section-title"><span>01</span><h2>{c.section}</h2><p>{c.note}</p></div><div className="extended-context-image"><img src={imageOf(lead)} alt={nameOf(lead, lang)} /><div><small>{c.detail}</small><strong>{nameOf(lead, lang)}</strong><span>{factsOf(lead, lang)}</span></div></div></section>
    <section id="extended-collection" className={`extended-collection extended-collection-${layout}`}><div className="extended-collection-head"><span>02 / HORIZON STAYS</span><h2>{layout === "compare" ? (ar(lang) ? "قارن الوحدات" : "Compare the stays") : c.section}</h2></div><div className="extended-stay-grid">{stays.slice(0, layout === "gallery" ? 6 : 4).map((stay, index) => <PropertyCard stay={stay} lang={lang} large={index === 0 && ["atelier", "edit", "gallery", "portfolio"].includes(layout)} key={stay.id} />)}</div></section>
    <section className={`extended-path extended-path-${layout}`}><div><span>03</span><h2>{ar(lang) ? "طريقك إلى الإقامة" : "Your route to a stay"}</h2></div><ol>{c.path.map((item, index) => <li key={item}><small>0{index + 1}</small><strong>{item}</strong><p>{ar(lang) ? "تفاصيل واضحة قبل الانتقال إلى الحجز." : "Clear details before moving into booking."}</p></li>)}</ol></section>
    <section className="extended-map"><div className="extended-section-title"><span>04</span><h2>{c.map}</h2><p>{ar(lang) ? "مرر فوق العلامة لمعاينة الوحدة، واضغط لتثبيت بطاقتها خارج الخريطة." : "Hover a marker to preview a stay, then click to pin its card outside the map."}</p></div><MapFrame locations={stays} lang={ar(lang) ? "ar" : "en"} variant="collection" /></section>
    <section className="extended-closing"><p>{ar(lang) ? "اختر الإقامة التي تناسب رحلتك، ثم افتح تفاصيلها وتواريخك." : "Choose the stay that fits your trip, then open its details and dates."}</p><Link to={`/property/${lead.slug}`}>{c.explore} <span>→</span></Link></section>
  </>;
}

export default function ExtendedThemeOptions({ option }: Props) {
  const { lang } = useLang(); const [stays, setStays] = useState<Property[]>([]); const [failed, setFailed] = useState(false); const theme = THEMES[option];
  useEffect(() => { fetchProperties().then(setStays).catch(() => setFailed(true)); }, []);
  const selection = useMemo(() => stays.slice(0, 8), [stays]);
  if (failed) return <section className="extended-loading">{ar(lang) ? "تعذر تجهيز الإقامات الآن." : "The stays could not be prepared right now."}</section>;
  if (!selection.length) return <section className="extended-loading">{ar(lang) ? "يتم تجهيز الإقامات…" : "Preparing stays…"}</section>;
  const fixed = imageOf(selection[0]);
  return <div className={`extended-option extended-${theme.style}`} dir={ar(lang) ? "rtl" : "ltr"}>
    <div className="extended-fixed-background" style={{ backgroundImage: `url(${fixed})` }} aria-hidden="true" />
    <div className="extended-page-surface"><RotatingHero stays={selection} theme={theme} lang={lang} /><DetailLayout theme={theme} stays={selection} lang={lang} /></div>
  </div>;
}
